[package]
name = "sustcsc-rs-bonus"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
rand = "0.9.2"
lll-rs = "0.2.0"
num-bigint = "0.4"
num-traits = "0.2"
rayon = "1.5"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
panic = 'abort'